In [1]:
import torch

In [10]:
emb = torch.nn.Embedding(3, 6)
emb
print(emb.weight.data)

tensor([[-1.6769, -1.6747,  0.0764, -1.4877, -1.4676,  0.9340],
        [ 0.5973, -1.5971,  0.5526, -2.1996,  0.9111,  0.1880],
        [-1.3009, -0.4647,  0.0252,  0.9853,  0.9807, -0.7044]])


In [11]:
train_data = torch.tensor([[0,1],[0,2],[1,2]], dtype= torch.long)
train_data.shape

torch.Size([3, 2])

In [14]:
x = emb(train_data)
print(x)
print(x.shape)

tensor([[[-1.6769, -1.6747,  0.0764, -1.4877, -1.4676,  0.9340],
         [ 0.5973, -1.5971,  0.5526, -2.1996,  0.9111,  0.1880]],

        [[-1.6769, -1.6747,  0.0764, -1.4877, -1.4676,  0.9340],
         [-1.3009, -0.4647,  0.0252,  0.9853,  0.9807, -0.7044]],

        [[ 0.5973, -1.5971,  0.5526, -2.1996,  0.9111,  0.1880],
         [-1.3009, -0.4647,  0.0252,  0.9853,  0.9807, -0.7044]]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([3, 2, 6])


In [33]:
a = torch.ones(3, 4)
print(a.t())
print(a)
b=  torch.t(a)
b[1] = b[1]*2
b[2] = b[2]*3
b[3] = b[3]*4

print(b)
print(b[:, 1:3])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])
tensor([[1., 1.],
        [2., 2.],
        [3., 3.],
        [4., 4.]])


In [40]:
a = torch.rand((3,2,4))
print(a)
print(a[:,0,:])
print(a[:,1,:])



tensor([[[0.4762, 0.2579, 0.6108, 0.5999],
         [0.2574, 0.9859, 0.6065, 0.4954]],

        [[0.7987, 0.8219, 0.2108, 0.3977],
         [0.4972, 0.3702, 0.3370, 0.3021]],

        [[0.5439, 0.8424, 0.6366, 0.6889],
         [0.5147, 0.6674, 0.8137, 0.4071]]])
tensor([[0.4762, 0.2579, 0.6108, 0.5999],
        [0.7987, 0.8219, 0.2108, 0.3977],
        [0.5439, 0.8424, 0.6366, 0.6889]])
tensor([[0.2574, 0.9859, 0.6065, 0.4954],
        [0.4972, 0.3702, 0.3370, 0.3021],
        [0.5147, 0.6674, 0.8137, 0.4071]])
